/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IconRouteImport } from './routes/icon'
import { Route as NestingRouteImport } from './routes/_nesting'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PageRouteImport } from './routes/$page'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TableIndexRouteImport } from './routes/table/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as UserPagerRouteImport } from './routes/user/pager'
import { Route as UserIdRouteImport } from './routes/user/$id'
import { Route as AboutIdRouteImport } from './routes/about/$id'
import { Route as NestingLayoutTestRouteImport } from './routes/_nesting/layout-test'
import { Route as NestingLayoutRouteImport } from './routes/_nesting/_layout'
import { Route as AuthPage2RouteImport } from './routes/_auth/page2'
import { Route as AuthPageRouteImport } from './routes/_auth/page'
import { Route as groupGroup3RouteImport } from './routes/(group)/group3'
import { Route as groupGroup2RouteImport } from './routes/(group)/group2'
import { Route as AboutNameIndexRouteImport } from './routes/about/name/index'
import { Route as AboutValueIndexRouteImport } from './routes/about/$value/index'
import { Route as AboutNameNameRouteImport } from './routes/about/name/$name'
import { Route as AboutValueCreateRouteImport } from './routes/about/$value/create'
import { Route as NestingLayoutTest2RouteImport } from './routes/_nesting/_layout/test2'
import { Route as NestingLayoutTest3IdRouteImport } from './routes/_nesting/_layout/test3.$id'

const UserLazyRouteImport = createFileRoute('/user')()
const StoreLazyRouteImport = createFileRoute('/store')()
const UserIndexLazyRouteImport = createFileRoute('/user/')()

const UserLazyRoute = UserLazyRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/user.lazy').then((d) => d.Route))
const StoreLazyRoute = StoreLazyRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/store.lazy').then((d) => d.Route))
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IconRoute = IconRouteImport.update({
  id: '/icon',
  path: '/icon',
  getParentRoute: () => rootRouteImport,
} as any)
const NestingRoute = NestingRouteImport.update({
  id: '/_nesting',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexLazyRoute = UserIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserLazyRoute,
} as any).lazy(() => import('./routes/user/index.lazy').then((d) => d.Route))
const TableIndexRoute = TableIndexRouteImport.update({
  id: '/table/',
  path: '/table/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPagerRoute = UserPagerRouteImport.update({
  id: '/pager',
  path: '/pager',
  getParentRoute: () => UserLazyRoute,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UserLazyRoute,
} as any)
const AboutIdRoute = AboutIdRouteImport.update({
  id: '/about/$id',
  path: '/about/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NestingLayoutTestRoute = NestingLayoutTestRouteImport.update({
  id: '/layout-test',
  path: '/layout-test',
  getParentRoute: () => NestingRoute,
} as any)
const NestingLayoutRoute = NestingLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => NestingRoute,
} as any)
const AuthPage2Route = AuthPage2RouteImport.update({
  id: '/page2',
  path: '/page2',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPageRoute = AuthPageRouteImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => AuthRoute,
} as any)
const groupGroup3Route = groupGroup3RouteImport.update({
  id: '/(group)/group3',
  path: '/group3',
  getParentRoute: () => rootRouteImport,
} as any)
const groupGroup2Route = groupGroup2RouteImport.update({
  id: '/(group)/group2',
  path: '/group2',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutNameIndexRoute = AboutNameIndexRouteImport.update({
  id: '/about/name/',
  path: '/about/name/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutValueIndexRoute = AboutValueIndexRouteImport.update({
  id: '/about/$value/',
  path: '/about/$value/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutNameNameRoute = AboutNameNameRouteImport.update({
  id: '/about/name/$name',
  path: '/about/name/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutValueCreateRoute = AboutValueCreateRouteImport.update({
  id: '/about/$value/create',
  path: '/about/$value/create',
  getParentRoute: () => rootRouteImport,
} as any)
const NestingLayoutTest2Route = NestingLayoutTest2RouteImport.update({
  id: '/test2',
  path: '/test2',
  getParentRoute: () => NestingLayoutRoute,
} as any)
const NestingLayoutTest3IdRoute = NestingLayoutTest3IdRouteImport.update({
  id: '/test3/$id',
  path: '/test3/$id',
  getParentRoute: () => NestingLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/icon': typeof IconRoute
  '/login': typeof LoginRoute
  '/store': typeof StoreLazyRoute
  '/user': typeof UserLazyRouteWithChildren
  '/group2': typeof groupGroup2Route
  '/group3': typeof groupGroup3Route
  '/page': typeof AuthPageRoute
  '/page2': typeof AuthPage2Route
  '/layout-test': typeof NestingLayoutTestRoute
  '/about/$id': typeof AboutIdRoute
  '/user/$id': typeof UserIdRoute
  '/user/pager': typeof UserPagerRoute
  '/about': typeof AboutIndexRoute
  '/table': typeof TableIndexRoute
  '/user/': typeof UserIndexLazyRoute
  '/test2': typeof NestingLayoutTest2Route
  '/about/$value/create': typeof AboutValueCreateRoute
  '/about/name/$name': typeof AboutNameNameRoute
  '/about/$value': typeof AboutValueIndexRoute
  '/about/name': typeof AboutNameIndexRoute
  '/test3/$id': typeof NestingLayoutTest3IdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/icon': typeof IconRoute
  '/login': typeof LoginRoute
  '/store': typeof StoreLazyRoute
  '/group2': typeof groupGroup2Route
  '/group3': typeof groupGroup3Route
  '/page': typeof AuthPageRoute
  '/page2': typeof AuthPage2Route
  '/layout-test': typeof NestingLayoutTestRoute
  '/about/$id': typeof AboutIdRoute
  '/user/$id': typeof UserIdRoute
  '/user/pager': typeof UserPagerRoute
  '/about': typeof AboutIndexRoute
  '/table': typeof TableIndexRoute
  '/user': typeof UserIndexLazyRoute
  '/test2': typeof NestingLayoutTest2Route
  '/about/$value/create': typeof AboutValueCreateRoute
  '/about/name/$name': typeof AboutNameNameRoute
  '/about/$value': typeof AboutValueIndexRoute
  '/about/name': typeof AboutNameIndexRoute
  '/test3/$id': typeof NestingLayoutTest3IdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_nesting': typeof NestingRouteWithChildren
  '/icon': typeof IconRoute
  '/login': typeof LoginRoute
  '/store': typeof StoreLazyRoute
  '/user': typeof UserLazyRouteWithChildren
  '/(group)/group2': typeof groupGroup2Route
  '/(group)/group3': typeof groupGroup3Route
  '/_auth/page': typeof AuthPageRoute
  '/_auth/page2': typeof AuthPage2Route
  '/_nesting/_layout': typeof NestingLayoutRouteWithChildren
  '/_nesting/layout-test': typeof NestingLayoutTestRoute
  '/about/$id': typeof AboutIdRoute
  '/user/$id': typeof UserIdRoute
  '/user/pager': typeof UserPagerRoute
  '/about/': typeof AboutIndexRoute
  '/table/': typeof TableIndexRoute
  '/user/': typeof UserIndexLazyRoute
  '/_nesting/_layout/test2': typeof NestingLayoutTest2Route
  '/about/$value/create': typeof AboutValueCreateRoute
  '/about/name/$name': typeof AboutNameNameRoute
  '/about/$value/': typeof AboutValueIndexRoute
  '/about/name/': typeof AboutNameIndexRoute
  '/_nesting/_layout/test3/$id': typeof NestingLayoutTest3IdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$page'
    | '/icon'
    | '/login'
    | '/store'
    | '/user'
    | '/group2'
    | '/group3'
    | '/page'
    | '/page2'
    | '/layout-test'
    | '/about/$id'
    | '/user/$id'
    | '/user/pager'
    | '/about'
    | '/table'
    | '/user/'
    | '/test2'
    | '/about/$value/create'
    | '/about/name/$name'
    | '/about/$value'
    | '/about/name'
    | '/test3/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$page'
    | '/icon'
    | '/login'
    | '/store'
    | '/group2'
    | '/group3'
    | '/page'
    | '/page2'
    | '/layout-test'
    | '/about/$id'
    | '/user/$id'
    | '/user/pager'
    | '/about'
    | '/table'
    | '/user'
    | '/test2'
    | '/about/$value/create'
    | '/about/name/$name'
    | '/about/$value'
    | '/about/name'
    | '/test3/$id'
  id:
    | '__root__'
    | '/'
    | '/$page'
    | '/_auth'
    | '/_nesting'
    | '/icon'
    | '/login'
    | '/store'
    | '/user'
    | '/(group)/group2'
    | '/(group)/group3'
    | '/_auth/page'
    | '/_auth/page2'
    | '/_nesting/_layout'
    | '/_nesting/layout-test'
    | '/about/$id'
    | '/user/$id'
    | '/user/pager'
    | '/about/'
    | '/table/'
    | '/user/'
    | '/_nesting/_layout/test2'
    | '/about/$value/create'
    | '/about/name/$name'
    | '/about/$value/'
    | '/about/name/'
    | '/_nesting/_layout/test3/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageRoute: typeof PageRoute
  AuthRoute: typeof AuthRouteWithChildren
  NestingRoute: typeof NestingRouteWithChildren
  IconRoute: typeof IconRoute
  LoginRoute: typeof LoginRoute
  StoreLazyRoute: typeof StoreLazyRoute
  UserLazyRoute: typeof UserLazyRouteWithChildren
  groupGroup2Route: typeof groupGroup2Route
  groupGroup3Route: typeof groupGroup3Route
  AboutIdRoute: typeof AboutIdRoute
  AboutIndexRoute: typeof AboutIndexRoute
  TableIndexRoute: typeof TableIndexRoute
  AboutValueCreateRoute: typeof AboutValueCreateRoute
  AboutNameNameRoute: typeof AboutNameNameRoute
  AboutValueIndexRoute: typeof AboutValueIndexRoute
  AboutNameIndexRoute: typeof AboutNameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icon': {
      id: '/icon'
      path: '/icon'
      fullPath: '/icon'
      preLoaderRoute: typeof IconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_nesting': {
      id: '/_nesting'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$page': {
      id: '/$page'
      path: '/$page'
      fullPath: '/$page'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexLazyRouteImport
      parentRoute: typeof UserLazyRoute
    }
    '/table/': {
      id: '/table/'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/pager': {
      id: '/user/pager'
      path: '/pager'
      fullPath: '/user/pager'
      preLoaderRoute: typeof UserPagerRouteImport
      parentRoute: typeof UserLazyRoute
    }
    '/user/$id': {
      id: '/user/$id'
      path: '/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof UserLazyRoute
    }
    '/about/$id': {
      id: '/about/$id'
      path: '/about/$id'
      fullPath: '/about/$id'
      preLoaderRoute: typeof AboutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_nesting/layout-test': {
      id: '/_nesting/layout-test'
      path: '/layout-test'
      fullPath: '/layout-test'
      preLoaderRoute: typeof NestingLayoutTestRouteImport
      parentRoute: typeof NestingRoute
    }
    '/_nesting/_layout': {
      id: '/_nesting/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NestingLayoutRouteImport
      parentRoute: typeof NestingRoute
    }
    '/_auth/page2': {
      id: '/_auth/page2'
      path: '/page2'
      fullPath: '/page2'
      preLoaderRoute: typeof AuthPage2RouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/page': {
      id: '/_auth/page'
      path: '/page'
      fullPath: '/page'
      preLoaderRoute: typeof AuthPageRouteImport
      parentRoute: typeof AuthRoute
    }
    '/(group)/group3': {
      id: '/(group)/group3'
      path: '/group3'
      fullPath: '/group3'
      preLoaderRoute: typeof groupGroup3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(group)/group2': {
      id: '/(group)/group2'
      path: '/group2'
      fullPath: '/group2'
      preLoaderRoute: typeof groupGroup2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/name/': {
      id: '/about/name/'
      path: '/about/name'
      fullPath: '/about/name'
      preLoaderRoute: typeof AboutNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/$value/': {
      id: '/about/$value/'
      path: '/about/$value'
      fullPath: '/about/$value'
      preLoaderRoute: typeof AboutValueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/name/$name': {
      id: '/about/name/$name'
      path: '/about/name/$name'
      fullPath: '/about/name/$name'
      preLoaderRoute: typeof AboutNameNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/$value/create': {
      id: '/about/$value/create'
      path: '/about/$value/create'
      fullPath: '/about/$value/create'
      preLoaderRoute: typeof AboutValueCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_nesting/_layout/test2': {
      id: '/_nesting/_layout/test2'
      path: '/test2'
      fullPath: '/test2'
      preLoaderRoute: typeof NestingLayoutTest2RouteImport
      parentRoute: typeof NestingLayoutRoute
    }
    '/_nesting/_layout/test3/$id': {
      id: '/_nesting/_layout/test3/$id'
      path: '/test3/$id'
      fullPath: '/test3/$id'
      preLoaderRoute: typeof NestingLayoutTest3IdRouteImport
      parentRoute: typeof NestingLayoutRoute
    }
  }
}

interface AuthRouteChildren {
  AuthPageRoute: typeof AuthPageRoute
  AuthPage2Route: typeof AuthPage2Route
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthPageRoute: AuthPageRoute,
  AuthPage2Route: AuthPage2Route,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface NestingLayoutRouteChildren {
  NestingLayoutTest2Route: typeof NestingLayoutTest2Route
  NestingLayoutTest3IdRoute: typeof NestingLayoutTest3IdRoute
}

const NestingLayoutRouteChildren: NestingLayoutRouteChildren = {
  NestingLayoutTest2Route: NestingLayoutTest2Route,
  NestingLayoutTest3IdRoute: NestingLayoutTest3IdRoute,
}

const NestingLayoutRouteWithChildren = NestingLayoutRoute._addFileChildren(
  NestingLayoutRouteChildren,
)

interface NestingRouteChildren {
  NestingLayoutRoute: typeof NestingLayoutRouteWithChildren
  NestingLayoutTestRoute: typeof NestingLayoutTestRoute
}

const NestingRouteChildren: NestingRouteChildren = {
  NestingLayoutRoute: NestingLayoutRouteWithChildren,
  NestingLayoutTestRoute: NestingLayoutTestRoute,
}

const NestingRouteWithChildren =
  NestingRoute._addFileChildren(NestingRouteChildren)

interface UserLazyRouteChildren {
  UserIdRoute: typeof UserIdRoute
  UserPagerRoute: typeof UserPagerRoute
  UserIndexLazyRoute: typeof UserIndexLazyRoute
}

const UserLazyRouteChildren: UserLazyRouteChildren = {
  UserIdRoute: UserIdRoute,
  UserPagerRoute: UserPagerRoute,
  UserIndexLazyRoute: UserIndexLazyRoute,
}

const UserLazyRouteWithChildren = UserLazyRoute._addFileChildren(
  UserLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageRoute: PageRoute,
  AuthRoute: AuthRouteWithChildren,
  NestingRoute: NestingRouteWithChildren,
  IconRoute: IconRoute,
  LoginRoute: LoginRoute,
  StoreLazyRoute: StoreLazyRoute,
  UserLazyRoute: UserLazyRouteWithChildren,
  groupGroup2Route: groupGroup2Route,
  groupGroup3Route: groupGroup3Route,
  AboutIdRoute: AboutIdRoute,
  AboutIndexRoute: AboutIndexRoute,
  TableIndexRoute: TableIndexRoute,
  AboutValueCreateRoute: AboutValueCreateRoute,
  AboutNameNameRoute: AboutNameNameRoute,
  AboutValueIndexRoute: AboutValueIndexRoute,
  AboutNameIndexRoute: AboutNameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
